unique_ids:
  assets:
    Screen Shot 2026-05-29 at 19.23.29.png: '1780065885052511879154244.10034'
    standard-page.html: RDF47MKR4YRXYH5SZOKWUKMMRVYM2M6I
    theme.css: 35LDG3F7PGNKCNTRD7YQQFETEXMSJUHZ
  forms:
    Form1: HLVRABCXTMH4IXI5NRXGRYULH7PB57MF
  modules: {}
  scripts: {}
  server_modules: {}
